version: "3.1"
services:

    webserver:
      image: nginx:latest
      container_name: hotsite-training-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8081:80"

    php-fpm:
      build: .
      container_name: hotsite-training-php-fpm
      working_dir: /application
      volumes:
          - .:/application